export {default as Navbar} from './Navbar'; 
export {default as Heading} from './Heading'; 
export {default as Milestones} from './Milestones'; 
export {default as Services} from './Services'; 
export {default as Work} from './Work'; 
export {default as Timeline} from './Timeline'; 
export {default as Testimonials} from './Testimonials'; 
export {default as Prefooter} from './Prefooter'; 
export {default as Footer} from './Footer'; 
